### ISSUE TITLE
Slight correction on the handling of errors

### ISSUE THREAD

**Issue by KevinJCross** [cloudfoundry/sample-http-app#3]
so this bit of the main.go is incorrect.
```
select {
	case err := <-errCh:
		fmt.Fprintln(os.Stderr, "error starting server:", err)
		os.Exit(1)
```
is not the correct way to handle this. In this code the return code will always be 1 and should be 0 for a successful graceful shutdown.
`server.Serve(listener)` always returns an error see https://pkg.go.dev/net/http#Server.Serve  always returns `ErrServerClosed`
so maybe the following would be better.

```go
select {
	case err := <-errCh:
                if !errors.Is(err, http.ErrServerClosed){
		   fmt.Fprintln(os.Stderr, "error starting server:", err)
		   os.Exit(1)
		}
		os.Exit(0)
```

**Comment by MarcPaquette** [comment]
Hi @KevinJCross,

Thanks for submitting this issue, and thanks for your patience as we're taking a more active role with our backlog.  We'd love to see a PR for this.

Thanks!

**Comment by MarcPaquette** [comment]
Fixed with https://github.com/cloudfoundry/sample-http-app/pull/5! Thanks for bringing this to our attention @KevinJCross
